apiVersion: v1
kind: Service
metadata:
  name: my-back-end-service-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: my-backend
  ports:
    - protocol: TCP
      port: 3000            # This is the port your app listens to inside the container
      targetPort: 3000       # The container port your Flask app is running on
      nodePort: 30007        # Optional: You can specify a NodePort or let Kubernetes assign one (default range: 30000-32767)
